### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ish12321** [theAsmodai/metamod-r#1]
Shall i use this or latest metamod p with rehlds , regamedll_cs

**Comment by theAsmodai** [comment]
Please wait for release.

**Comment by ish12321** [comment]
OK

**Comment by Phantomsq** [comment]
Asap

**Comment by ish12321** [comment]
Ready?

**Comment by ish12321** [comment]
BUMP ! READY ?

**Comment by stamepicmorg** [comment]
@ish12321 ready. u can try to use it with rehlds and regame. and do feedback here. if u want. why not.
