### ISSUE TITLE
[Half-Life 1 server error] Unrecognized game: valve (rehlds 3.0.0.5xx + metamod-r .66 or .73)

### ISSUE THREAD

**Issue by stamepicmorg** [theAsmodai/metamod-r#11]
1. half-life 1 сервер на windows. не counterstrike -> regame.dll отсутствует.
2. установлен свежий rehlds 3.0.0.578. (пробовал и на предпоследних).
3. при запуске сервера, при инициализации метамода происходит краш.
4. пробовал запускать чистый метамод без дополнений, вроде amxx и прочего.

**Comment by theAsmodai** [comment]
Try 1.3.73

**Comment by stamepicmorg** [comment]
i've already tryed .66 and 1.3.73  :(

**Comment by theAsmodai** [comment]
Ok then I need a crashdump.

**Comment by stamepicmorg** [comment]
done
[hlds.exe.3704.zip](https://github.com/theAsmodai/metamod-r/files/1140450/hlds.exe.3704.zip)

**Comment by theAsmodai** [comment]
Metamod can not load the gamedll. Check server logs.

**Comment by stamepicmorg** [comment]
ok. i will check it later. very strange..

maby because i am using [Bugfixed and improved HL release](http://aghl.ru/forum/viewtopic.php?f=32&t=686) (custom hl.dll)?

**Comment by stamepicmorg** [comment]
okay. i think, i catched error. metamod cant recognize "valve" game. see qconsole log below. and metamod trying to fing plugins.ini file at addons-folder.

-----------

my steps to reproduce the prob
[hlds.exe.2644.zip](https://github.com/theAsmodai/metamod-r/files/1143598/hlds.exe.2644.zip)

lem.

windows 10, x64, 1703 build, russian system locale.
1. downloadded via steamcmd new server with 7xxx build.
2. installed rehlds 3.0.0.580.
3. installed metamod-r 1.3.73 without any plagins (like amxmodx). just metamod-r.
4. server crashes.

------------

start arguments:

> hlds.exe -console -condebug +log on -dev

steamcmd:

> steamcmd +login anonymous +force_install_dir "%SERVER_PATH%" +app_set_config 90 mod valve +app_update 90 validate +quit

liblist.gam:

> // Valve Game Info file
> //  These are key/value pairs.  Certain mods will use different settings.
> //
> game "Half-Life"
> startmap "c0a0"
> trainmap "t0a0"
> mpentity "info_player_deathmatch"
> gamedll "addons\metamod\metamod.dll"
> gamedll_linux "dlls/hl.so"
> gamedll_osx "dlls/hl.dylib"
> secure "1"
> type "singleplayer_only"

qconsole log:

Console initialized.
Base networking initialized.
"sv_cheats" changed to "1"
Initializing deltas
Protocol version 48
Exe version 1.1.2.2/Stdio (valve)
Exe build: 21:01:25 Jul 11 2017 (1186)
"sv_version" changed to "1.1.2.2/Stdio,48,1186"
40.0 Mb heap
execing valve.rc
execing language.cfg
execing autoexec.cfg
execing violence.cfg
Server logging data to file logs\L0713004.log
L 07/13/2017 - 02:24:06: Log file started (file "logs\L0713004.log") (game "valve") (version "48/1.1.2.2/Stdio/1186")
Server IP address 192.168.1.15:27015
Could not get IPX address, IPX disabled
Reason:  WSAENOTSOCK

Adding:  valve/addons\metamod\metamod.dll
L 07/13/2017 - 02:24:06: [META] dev: called: GiveFnptrsToDll
   
   Metamod-r version 1.3.73 Copyright (c) 2016-2017 ReHlds Team (rebuild of original Metamod by Will Day)
   Metamod-r comes with ABSOLUTELY NO WARRANTY; for details type `meta gpl'.
   This is free software, and you are welcome to redistribute it
   under certain conditions; type `meta gpl' for details.
   
Metamod-r v1.3.73, API (5:13)
Metamod-r build: 22:25:38 Jul  6 2017 (1.3.73)
Metamod-r from: https://github.com/theAsmodai/metamod-r/commit/daea1f8 (asmodai)
L 07/13/2017 - 02:24:06: [META] (debug:3) set config int: debuglevel = 0
L 07/13/2017 - 02:24:06: [META] (debug:3) set config bool: clientmeta = false
L 07/13/2017 - 02:24:06: [META] (debug:2) Loading from config file: c:/users/epicmorg/desktop/t/valve/addons/metamod/config.ini
L 07/13/2017 - 02:24:06: [META] (debug:3) set config int: debuglevel = 42
L 07/13/2017 - 02:24:06: [META] (debug:3) set config bool: clientmeta = false
L 07/13/2017 - 02:24:06: [META] (debug:5) Empty file: c:/users/epicmorg/desktop/t/valve/addons/metamod/plugins.ini
L 07/13/2017 - 02:24:06: [META] (debug:5) Unable to stat **'c:/users/epicmorg/desktop/t/valve/addons/plugins.ini': No such file or directory**
L 07/13/2017 - 02:24:06: [META] (debug:2) No plugins.ini file found: plugins.ini
L 07/13/2017 - 02:24:06: **[META] ERROR: dll: Unrecognized game: valve**
L 07/13/2017 - 02:24:06: [META] **ERROR: Failure to load game DLL; exiting...**


my dump file:
[hlds.exe.2644.zip](https://github.com/theAsmodai/metamod-r/files/1143600/hlds.exe.2644.zip)

**Comment by WPMGPRoSToTeMa** [comment]
Try to add `-game valve +map crossfire -maxplayers 32`

**Comment by stamepicmorg** [comment]
a day ago i tried at production server (with other arguments. like -game, +map, etc). ok. i am added other arguments at new test server (form [this comment](https://github.com/theAsmodai/metamod-r/issues/11#issuecomment-314926146)). _same problem._

**Comment by Phantomsq** [comment]
@stamepicmorg, now you can check it again and say, will everything work or not

**Comment by stamepicmorg** [comment]
@Phantomsq, ok. I will try with new build [1.3.76 (17 Jul 17 19:59)](http://teamcity.rehlds.org/viewLog.html?buildId=8996&tab=artifacts&buildTypeId=Metamod_Windows).
