### ISSUE TITLE
[question] support of official valve-mods like tfc, dod, etc?

### ISSUE THREAD

**Issue by stamepicmorg** [theAsmodai/metamod-r#14]
**Just a question**. Can you add to the metamod-r support for official modifications that are available for download through the steamcmd and have official support of amxx? I [know](https://github.com/theAsmodai/metamod-r/pull/12) about custom loading a dll from config ini.

This mods succussfully works with rehlds (tested).

I'm just curious and I'm sorry... 😄 

### official valve mods:
[name]. [folder]. [dll]. [so]

Ricochet: ricochet, mp.dll, ricochet.so
Counter-Strike:Condition Zero, Deleted scenes: czeror, cz.dll,cz.so
DeathMatch Classic: dmc, dmc.dll, dmc.so
Day of Defeat: dod, dod.dll, dod.so
Team Fortress Classic: tfc, tfc.dll ,tfc.so

### ~3rd party:~
~Natural Selection: ns, ns.dll, ns_i386.so~
~The Specialists: ts, mp.dll, ts_i386.so, ts_i686.so~

**Comment by Phantomsq** [comment]
Why do you need this? Do specifically you hosts any servers besides Counter-Strike 1.6?

**Comment by Phantomsq** [comment]
ADD: CS:CZ is already supports metamod-r

**Comment by stamepicmorg** [comment]
> Do specifically you hosts any servers besides Counter-Strike 1.6?
yes. hl1 servers, Ricochet (lol, why?), Natural Selection and The Specialists 3.0..

> Why do you need this? 
i dont. i can add path in my config manually. but original metamod supports this list of mods, and this metamod-r not. and i have this question.

**Comment by stamepicmorg** [comment]
thanks!  ❤️
