### ISSUE TITLE
[question] actually a few

### ISSUE THREAD

**Issue by krangm** [theAsmodai/metamod-r#17]
hello i've got a few questions
please pardon me if they might be silly

1. does this metamod better than [p39](https://github.com/SamVanheer/Metamod-P-CMake)?
any criteria (faster/more stable/whatever)

2. does it support Adrenaline Gamer?
if no, do you plan to add support?

3. does it support Sven Coop 5.xx ?
if no, do you plan to add support?

thanks in advance

**Comment by Phantomsq** [comment]
1.  Metamod-r is faster
2. Metamod-r supports AG
3. I think, yes, but you must manually load you need mode. Read this: https://github.com/theAsmodai/metamod-r/blob/master/metamod/extra/config.ini#L31

**Comment by stamepicmorg** [comment]
**krangm**
> does it support Adrenaline Gamer?
> if no, do you plan to add support?
> 
> does it support Sven Coop 5.xx ?
> if no, do you plan to add support?

**theAsmodai** 
> I think, yes, but you must manually load you need game binary (.dll/.so). Read this: 

@krangm, now Metamod-r is fully  [supported](https://github.com/theAsmodai/metamod-r/blob/master/metamod/src/game_support.cpp) AG\OpenAG and SvenCoop. See [README.MD](https://github.com/theAsmodai/metamod-r/blob/master/README.md) file with compablity list.

**Comment by krangm** [comment]
@stamepicmorg OpenAG is just a client, doubt its related to metamod anyhow. In common yes, AG servers working fine with metamod-r but cant tell same about Sven Co-op 5.xx. At least on default HLSP maps server becomes critically unstable with metamod (any, not only -r). Server fps drops to nearly 20, player pings grow to ~+150 from what they had without metamod. Feels awful and unplayable.
Guess this is more Sven Co-op problem rather than metamod but still cant say game is 'fully supported'.

**Comment by stamepicmorg** [comment]
Maby if 

>HLSP maps server becomes critically unstable with metamod (any, not only -r)

Problem not at metamods?

**Comment by stamepicmorg** [comment]
@krangm hello! problem resolved [here](https://github.com/theAsmodai/metamod-r/issues/45).

**Comment by stamepicmorg** [comment]
@krangm hello! problem resolved [here](https://github.com/theAsmodai/metamod-r/issues/45).
