### ISSUE TITLE
Cant compile

### ISSUE THREAD

**Issue by nksiddhant** [theAsmodai/metamod-r#18]
./Makefile: line 1: COMPILER: command not found
./Makefile: line 2: SDKSRC: command not found
./Makefile: line 3: DIRSRC: command not found
./Makefile: line 4: NAME: command not found
./Makefile: line 6: SRCFILES: command not found
./Makefile: line 12: SRCFILES: command not found
./Makefile: line 12: OBJECTS: command not found
./Makefile: line 14: LINK: command not found
./Makefile: line 16: OPT_FLAGS: command not found
./Makefile: line 19: DIRSRC: command not found
./Makefile: line 19: SDKSRC: command not found
./Makefile: line 19: SDKSRC: command not found
./Makefile: line 19: SDKSRC: command not found
./Makefile: line 19: SDKSRC: command not found
./Makefile: line 19: INCLUDE: command not found
./Makefile: line 21: BIN_DIR: command not found
./Makefile: line 22: OPT_FLAGS: command not found
./Makefile: line 22: CFLAGS: command not found
./Makefile: line 24: CFLAGS: command not found
./Makefile: line 26: BIN_DIR: command not found
./Makefile: line 26: OBJECTS:%.c=/%.o: No such file or directory
./Makefile: line 26: OBJ_LINUX: command not found
./Makefile: line 28: BIN_DIR: command not found
./Makefile: line 28: /%.o:: No such file or directory
./Makefile: line 29: syntax error near unexpected token `newline'
./Makefile: line 29: `  $(COMPILER) $(INCLUDE) $(CFLAGS) -o $@ -c $<'

**Comment by voed** [comment]
Try to use gradle instead of makefile

**Comment by stamepicmorg** [comment]
@nksiddhant how are there?
