### ISSUE TITLE
Precompiled metamod-r ?

### ISSUE THREAD

**Issue by fred0r** [theAsmodai/metamod-r#19]
Please provide a working compile of the latest git for Linux and Windows.

**Comment by justgo97** [comment]
https://github.com/theAsmodai/metamod-r/releases

**Comment by stamepicmorg** [comment]
or just click on blue button (with version) on main page of this repo.

or use this link: http://teamcity.rehlds.org/guestAuth/downloadArtifacts.html?buildTypeId=Metamod_Publish&buildId=lastSuccessful

**Comment by fred0r** [comment]
@justgo97 : thx - haven't seen it before, but this isn't the latest build.
@stamepicmorg : thank you
