### ISSUE TITLE
Проблемы...

### ISSUE THREAD

**Issue by neygomon** [theAsmodai/metamod-r#2]
Все работает кроме плагинов с MYSQL.
Они тупо никак не инициализируются...
статус running, НО функций никаких не выполняют.
Иногда проскакивают мессаги, что запрос кривой, но на старой версии меты, не форка твоего, все ок.

Так же - amxmodx сыпет 
L 02/14/2017 - 09:41:41: [(null)] GetForceCamera : Can't suppress original function call without new return value set
L 02/14/2017 - 09:41:41: [(null)] GetForceCamera : Can't suppress original function call without new return value set
L 02/14/2017 - 09:41:41: [(null)] GetForceCamera : Can't suppress original function call without new return value set
L 02/14/2017 - 09:41:41: [(null)] GetForceCamera : Can't suppress original function call without new return value set
L 02/14/2017 - 09:41:41: [(null)] Observer_IsValidTarget : Can't suppress original function call without new return value set
L 02/14/2017 - 09:41:41: [(null)] Observer_IsValidTarget : Can't suppress original function call without new return value set
L 02/14/2017 - 09:41:41: [(null)] Observer_IsValidTarget : Can't suppress original function call without new return value set
L 02/14/2017 - 09:41:41: [(null)] Observer_IsValidTarget : Can't suppress original function call without new return value set
L 02/14/2017 - 09:41:41: [(null)] Observer_IsValidTarget : Can't suppress original function call without new return value set

Логи, я так думаю, от него [adminfreelook.zip](https://github.com/theAsmodai/metamod-r/files/774446/adminfreelook.zip)

и нету clientmeta no, за это -100 в карму тебе 👎

**Comment by Phantomsq** [comment]
@theAsmodai, add "clientmeta no" command, плиз

**Comment by WPMGPRoSToTeMa** [comment]
I think `clientmeta no` should be by default, like `amx_plugins`.

**Comment by theAsmodai** [comment]
fixed
