### ISSUE TITLE
Team Score Swap crash server

### ISSUE THREAD

**Issue by Zetz512** [theAsmodai/metamod-r#21]
hi, i recently testing the plugin Mix Maker (modified with reapi)
i use the last metamod-r 1.3.0.84 and i have constantly crashes after round 15 end to round 16 (swap score & team) and thats works fine on metamod-p
After many tries to see where is the problem i can see that come from UpdateTeamScore or from
	register_message(get_user_msgid("TeamScore"), "MessageTeamScore") where exec the UpdateTeamScore stock...

and that stock swap the scores of team to do not lose that scores and start again on CT:0-T:0

and to fix it i change the metamod-r to metamod-p37

i dont have any crash dump because i don't see anything like that and i don't know how to generate it...

**Comment by stamepicmorg** [comment]
@zetz512 hello! How are there? U have still problem?

If server crashes and restarting crashdumps generating automaticly. Soon u can read at wiki how to get them. But yet u can google for it.

**Comment by stamepicmorg** [comment]
no any feedback. closing as invalid.
