### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ish12321** [theAsmodai/metamod-r#22]
I dont know if this is correct place to ask help or not...

My server randomly at any time daily stops responding to players for few minutes like if its a crash but then in few mins it responds again confirming it wasnt a crash.
The server generates no logs..
Is there anyone who could please help me.?

**Comment by ish12321** [comment]
After helps from my friend i found out its server query flooding coming from various ip because f which server aint able to ban ip due to different IP doing it..

Any help?

**Comment by theAsmodai** [comment]
It's doesn't refer to metamod.
