### ISSUE TITLE
NoSeeVar 2.0

### ISSUE THREAD

**Issue by ArmynC** [theAsmodai/metamod-r#26]
I got NoSeeVar and in console it give me:

>     NoSeeVar: meta-interface version mismatch (metamod: 5:13, NoSeeVar: 5:10)
>     NoSeeVar: plugin attaching

**Isn't related directly to Metamod-R but is about NoSeeVar compatibilty with Metamod (R?), so I need some assistance..**

**Comment by theAsmodai** [comment]
You need to recompile NoSeeVar with newest hlsdk version.

**Comment by stamepicmorg** [comment]
@ArmynC how are u?

**Comment by ArmynC** [comment]
@stamepicmorg I just deleted it and .. put an amxx plugin..

**Comment by stamepicmorg** [comment]
O
