### ISSUE TITLE
add wiki to this repo please

### ISSUE THREAD

**Issue by stamepicmorg** [theAsmodai/metamod-r#30]
@theAsmodai Can u (or somebody else) add wiki to this repo in settings please and permissions for me? i want to write some documentation with installing  examples and troubleshoting tips.

**Comment by theAsmodai** [comment]
you are welcome

**Comment by stamepicmorg** [comment]
thank u 👍

**Comment by stamepicmorg** [comment]
temporary writing it [here](https://github.com/EpicMorgGames/metamod-r-game-tests/wiki)
soon i will move it to this repo.

**Comment by stamepicmorg** [comment]
@theAsmodai hello again. can u add user @AEnimka  to wiki  please? she translating wiki in to english and very helping me.
