### ISSUE TITLE
README.md: Metamod should be credited to Will Day

### ISSUE THREAD

**Issue by jkivilin** [theAsmodai/metamod-r#31]
I think README.md should be updated to credit Metamod to Will Day, the true author of the plugin, and not to some random guy that took the source and made few hacks on top of it ;)

**Comment by wopox1337** [comment]
Oh....

**Comment by stamepicmorg** [comment]
@jkivilin hello! Done: https://github.com/theAsmodai/metamod-r/commit/c7c3494bd00d67268ab11f880f5e6c5de4bc39a2

**Comment by stamepicmorg** [comment]
Close?

**Comment by jkivilin** [comment]
Yes, thanks :)

**Comment by stamepicmorg** [comment]
Have a nice day ^_^
