### ISSUE TITLE
Problem with parsing of game_support.cpp during loading mod's library via metamod-r

### ISSUE THREAD

**Issue by AEnimka** [theAsmodai/metamod-r#33]
## Enviroment:
* Windows 10 x64 \ Ubuntu 16.04 TLS x64 server
* Metamod-R 1.3.0.117 and older.
* Original hlds 6xxx\7xxx build  or rehlds (any 3.x buld)
* sven coop game 5.x (steam)

----

## Problems

1. Metamod-r doesn't change binary file according to requrements. It always uses the first binary by default (.so or .dll file) even if there are several folder's names. For example, it uses hl.so\hl.dll only in all cases (StargateTC) or hl.dll (Sven Coop 5.x).

#### Affected games:

```
{ "stargatetc",    "hl.so",     "hl.dll",     "StargateTC (Old, 1.x)"    },
{ "stargatetc",     "stc.so",     "hl.dll",      "StargateTC (Updated, 2.x)"    }, // _i386.so
{ "stargatetc",      "stc_i386_opt.so",    "hl.dll",    "StargateTC (Updated, 2.x)"    },
```
and
```
{ "svencoop",    "hl.so",     "hl.dll",     "Sven Coop (Old)"    },
{ "svencoop",    "server.so",    "server.dll",    "Sven Coop (Steam)"    },
```
2. Setting of `gamedll` (config.ini) doesn't help for the bug above.

**Comment by stamepicmorg** [comment]
Confirmed that [here](https://github.com/theAsmodai/metamod-r/issues/17#issuecomment-362253473) today with svencoop (windows)..

 :(
