### ISSUE TITLE
Official site

### ISSUE THREAD

**Issue by stamepicmorg** [theAsmodai/metamod-r#35]
@theAsmodai Hello!

I've got a domain name - https://metamod-r.org/ (it is just html landing with links to this repo. no files, just official links. sources [here](https://github.com/EpicMorg/metamod-r.org)).

If u want i can give to you full-acess to server's folder with site or sub-links\subdomains to your's ip's (i can set it up at my nginx).

U can write me at steam (we are friends there), vk or telegram, emails, etc

Can u accept as official site?

**Comment by theAsmodai** [comment]
ok

**Comment by stamepicmorg** [comment]
👍
