### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by ish12321** [theAsmodai/metamod-r#37]
Hey,
My server is crashing. I don't know what it is. Could someone tell me how to get detailed crash report or something with which I can know what is causing it and maybe eventually get it solved.

**Comment by ish12321** [comment]
Ubuntu 17.10
Latest version of rehlds and metamod-r

**Comment by ish12321** [comment]
Installed gdb and did -debug and the ulimited line. Server now crashed. Where will be its report located ?

**Comment by stamepicmorg** [comment]
@theAsmodai we need ur help..

**Comment by ish12321** [comment]
I did echo 1 > /proc/sys/kernel/core_uses_pid
In / directory I find only core.so

**Comment by ish12321** [comment]
Dropped -=mbaD=-GaminG*[Kz] from server

Reason:  [ SpeedRun Detected ]

OGP_HOME_000000027_startup_scr.sh: line 2:  1445 Segmentation fault      (core dumped) taskset -c 0 ./hlds_run -game cstrike -pidfile ogp_game_startup.pid +map de_dust2 +ip 103.78.121.106 +port 27015 +maxplayers 32 -norestart -condebug

Server 'taskset -c 0 ./hlds_run -game cstrike -pidfile ogp_game_startup.pid +map de_dust2 +ip 103.78.121.106 +port 27015 +maxplayers 32 -norestart -condebug' crashed with exit code 0.  Respawning...

**Comment by ish12321** [comment]
My ReSRDetector config : 
LogMode = 2

SpeedRun_Warn = 9
SpeedRun_Reset = 50.0
SpeedRun_Punish_Kill = 0

PunishStringSpeedRun = 

NameSpam_Enable = 1
NameSpam_Type = 0
NameSpam_Warn = 5
NameSpam_Wait = 10.0

PunishStringNameSpam = amx_ban 43200 [userid] "NameSpam Detected"

**Comment by ish12321** [comment]
@theAsmodai 
Is it something I'm doing wrong in your ReSRDetector ?

**Comment by theAsmodai** [comment]
It's not mine.

**Comment by stamepicmorg** [comment]
The author of "ReSRDetector" is @Adidasman1. 

@ish12321, there is official support topic here: http://aghl.ru/forum/viewtopic.php?f=19&t=2350
