### ISSUE TITLE
latest metamod not loading Adrenaline Gamer gamedll out of the box

### ISSUE THREAD

**Issue by krangm** [theAsmodai/metamod-r#38]
v1.3.0.121
probably because of this
https://github.com/theAsmodai/metamod-r/blob/89b29af8a5ae671f3c78403d055dff48d3a0a6ce/metamod/src/game_support.cpp#L14
original gamedll name is `ag_i386.so` and not just `ag.so`
so to run server you gotta manually point metamod to gamedll in `config.ini`

tho i had not this problem on metamod v1.3.0.104

**Comment by krangm** [comment]
> // .so file by OpenAG fork

OpenAG pack designed to run or regular HLDS, where you really need to rename `ag_i386.so` to `ag.so` for successful run.
while ReHLDS has this problem fixed and allow to run original named gamedll without any changes

**Comment by stamepicmorg** [comment]
about "_i386.so"-postfix look [hrere](https://github.com/theAsmodai/metamod-r/issues/33) and [here](https://github.com/theAsmodai/metamod-r/commit/35eada44d065cf00f1fd3c9ecfca6ec91b52d11d).

> probably because of this
nope. current version of metamod-r detects "_i386\_i486\_i686" postfixes automaticly.

 @theAsmodai  right?

____

> OpenAG pack designed to run or regular HLDS
i have mistake at this description. OpenAG its just alternative client and it has no server's dll. If u runing

**Comment by krangm** [comment]
> are u using hlds or rehlds?

obv im running ReHLDS, moveover metamod-r no longer supports original HLDS

>OpenAG its just alternative client and it has no server's dll. If u will runing AG-server (also with installed client.dll from openAG) - u will be running originalAG-server.

i know that. i meant OpenAG full pack contains both client and server libs, and i know that server one is native AG gamedll. but once again OpenAG full pack designed to run on regular HLDS so they have already renamed server gamedll from `ag_i386.so` to `ag.so` to avoid this kind of errors
```
LoadLibrary failed on p▒▒▒▒▒▒M▒p▒▒▒▒▒▒/▒▒▒▒▒: p▒▒▒▒▒▒M▒p▒▒▒▒▒▒/▒▒▒▒▒: cannot open shared object file: No such file or directory
Host_Error: Couldn't get DLL API from p▒▒▒▒▒▒M▒p▒▒▒▒▒▒/▒▒▒▒▒!
FATAL ERROR (shutting down): Host_Error: Couldn't get DLL API from p▒▒▒▒▒▒M▒p▒▒▒▒▒▒/▒▒▒▒▒!
```

gamedll name is crucial for regular HLDS, but since metamod-r now works only with ReHLDS the only gamedll name that will work is `ag_i386.so`

**Comment by theAsmodai** [comment]
No, postfixes are not automatically checked for gamedll.

**Comment by stamepicmorg** [comment]
@theAsmodai 
> No, postfixes are not automatically checked for gamedll.

But
```
const char* g_platform_postfixes[4] =
{
	"_i386.so",
	"_i486.so",
	"_i586.so",
	"_i686.so",
};
```

https://github.com/theAsmodai/metamod-r/blob/master/metamod/src/utils.cpp

**Comment by theAsmodai** [comment]
It's only for plugins.ini

**Comment by stamepicmorg** [comment]
> It's only for plugins.ini

I was misinformed. Sorry. I will be  fix this list soon with PR.
