### ISSUE TITLE
Deathrun Manager (xpaw) crash server.

### ISSUE THREAD

**Issue by stambeto2006** [theAsmodai/metamod-r#40]
Metamod-r does not work with Deathrun Manager (xpaw) and crash server. With Metamod version 1.21p37 has no problems and does not crash the server. This crash problem does so at the very beginning when he determines the players' teams at the start of the round.

https://github.com/s1lentq/ReGameDLL_CS/issues/215

A lot of time has passed and this problem has not yet been resolved, Metamod-p 1.21p37 can not have any problems and work, and Metamod-r will crashes the server.

Dump File  ---->  http://www.mediafire.com/file/3wi6295wslo69wu/hlds.exe.348040.rar

**Comment by stambeto2006** [comment]
@theAsmodai @stamepicmorg When will this problem be solved with a metamod-r to be able to use the latest versions for deathrun server, without any problems with the server?

**Comment by stambeto2006** [comment]
@theAsmodai @stamepicmorg 
Metamod-r is not intended for DeathRun server.
Metamod version 1.21p37 has been working on my server for a long time and has never done a problem before, but when I changed his metamod with metamod-r the latest one that developed and started crashing

**Comment by stamepicmorg** [comment]
@stambeto2006,

Are u using win10 or win 7? Your systeam is x86, right?

**Comment by stambeto2006** [comment]
It does not help, its problem is only in Metamod-r
Metamod 1.21p37 and 1.21p38 there are no problems , only Metamod-r server is crashing for deathrun server

**Comment by s1lentq** [comment]
@stambeto2006 check out last version

**Comment by s1lentq** [comment]
@stambeto2006 you have messenger? tg, icq or qip, anything

**Comment by stambeto2006** [comment]
@s1lentq 
tg, icq or qip  i dont have
do you have skype?

**Comment by s1lentq** [comment]
@stambeto2006 live:s1lentsk

**Comment by stambeto2006** [comment]
@s1lentq done

**Comment by stambeto2006** [comment]
I found another problem that conflicts with crashing the server when you use the DeathRun plugin under the new metamod-r. I use a plugin for a long time that works without any problems with older versions of metamod, and when I use it with the latest metamod-r and the Deathrun plugin is included and the server crashes.
When there are more than two people on the server, and you have to choose who to be a terrorist.
I have sent two problems to the plugins that crash in the newest metamod-r.

@s1lentq Let me fix these issues that I sent you to skype.

**Comment by stambeto2006** [comment]
@s1lentq @theAsmodai What has happened to the problem will it be fixed soon or again not.
Because of this problem many servers do not use the metamod-r for deathrun servers.

**Comment by germansassone** [comment]
Video: https://youtu.be/PNKqp-KeTw8

Dumps: [dumps.zip](https://github.com/theAsmodai/metamod-r/files/2060044/dumps.zip)

Sorry for the delay

**Comment by stambeto2006** [comment]
@germansassone  This is not just the problem, even when the main plugin is released, it is starting to cause problems with other plugins and crashes the server again. When the main plugin is stopped, the other plugins work without any problem.

**Comment by basuritashka** [comment]
Can confirm, happened to me aswell.

**Comment by stambeto2006** [comment]
Will there be any development on the issue soon or have you already forgotten it?
@s1lentq He told me in two days that it would be fixed, but it's been a long time and without any development? I'm not the only person who has these problems, and other people have it.

**Comment by s1lentq** [comment]
@stambeto2006 sry for not fixing a long time, I just hoped it would be fixed by @theAsmodai, because he has skills with asmjit higher than me

**Comment by stambeto2006** [comment]
@s1lentq The problem is not fixed in the new version, so here is a dumps file attachment

[hlds.exe.21104.zip](https://github.com/theAsmodai/metamod-r/files/2106002/hlds.exe.21104.zip)

**Comment by stambeto2006** [comment]
@theAsmodai @s1lentq 
Asmodai Will you get involved with tackling this problem I have mentioned?

**Comment by basuritashka** [comment]
Hello?

**Comment by stambeto2006** [comment]
Can you solve this problem after a year?

**Comment by theAsmodai** [comment]
fixed.
