### ISSUE TITLE
Problem compiling with ICC 19

### ISSUE THREAD

**Issue by vladsol** [theAsmodai/metamod-r#44]
https://github.com/theAsmodai/metamod-r/blob/0cf2f709dbeae18ca84d2fafd4481ffbba06ad0c/metamod/src/sys_module.cpp#L145

Is it ok to use "false" here? Looks like ICC don't like that.
/home/user/build/metamod-r/metamod/src/sys_module.cpp(145): error: return value type does not match the function type
                return false;
                       ^

**Comment by WPMGPRoSToTeMa** [comment]
There should be `INVALID_HANDLE`.

**Comment by stamepicmorg** [comment]
fixed
