### ISSUE TITLE
team is full issue

### ISSUE THREAD

**Issue by RauliTop** [theAsmodai/metamod-r#48]
Tested on a local server with Windows.
Game: Counter-Strike 1.6 with ReHLDS
New server without modules or plugins, only Metamod-r.

You can't select a team because server says they are full.
![metamod-r_bug](https://user-images.githubusercontent.com/13453517/77848917-4435dd00-71c8-11ea-9d21-c83f3d7cf4dd.png)

**Comment by RauliTop** [comment]
Reported years ago, but not useful information:
https://github.com/theAsmodai/metamod-r/issues/34

**Comment by SmileYzn** [comment]
This is related to local lan server, not rehlds itself. But i can use rehlds on client? Also with metamod-r?
I mean, is supposed to work, directly in client side.

**Comment by wopox1337** [comment]
[From README](https://github.com/theAsmodai/metamod-r/blob/adc94141a4b11389ab7669034984c4d3bc13c9b3/README.md)
> **Metamod-r is incompatible with original HLDS. It's necessary to have installed [ReHLDS](https://github.com/dreamstalker/ReHLDS) (API 3.1+). There is no guarantee that the product will work in a different environment.**
