### ISSUE TITLE
Автобилд

### ISSUE THREAD

**Issue by Aleks-Z** [theAsmodai/metamod-r#5]
Можешь сделать автобилд как у ReHLDS ? 
[Пример](http://nexus.rehlds.org/nexus/content/repositories/rehlds-dev/rehlds/rehlds/)
PS Возможно пригодиться, но это просто ребилд на CMake
[Metamod-P-CMake](https://github.com/SamVanheer/Metamod-P-CMake)

**Comment by Phantomsq** [comment]
Metamod-plugin isn't ready now, i think it's too early to talk about "autobuild" as you say

**Comment by theAsmodai** [comment]
We already added this project to teamcity but it hidden now.

**Comment by stamepicmorg** [comment]
maby close this issue? :)
