### ISSUE TITLE
Compiling Problem

### ISSUE THREAD

**Issue by illiaKuryaki** [theAsmodai/metamod-r#54]
Hi, i was trying to compile metamod-r version 1.3.0.128, but i cant, it seems that get stuck connecting to nexus.rehlds.org, i got javac 1.7.0_80, and icc (ICC) 2021.4.0 20210910 

18:46:29.016 [DEBUG] [org.gradle.internal.resource.transport.http.HttpResourceAccessor] Constructing external resource metadata: http://nexus.rehlds.org/nexus/content/repositories/rehlds-snapshots/joda-time/joda-time/2.7/joda-time-2.7.pom
18:46:29.017 [DEBUG] [org.gradle.internal.resource.transport.http.HttpClientHelper] Performing HTTP HEAD: http://nexus.rehlds.org/nexus/content/repositories/rehlds-snapshots/joda-time/joda-time/2.7/joda-time-2.7.pom
18:46:29.019 [DEBUG] [org.apache.http.impl.conn.PoolingClientConnectionManager] Connection request: [route: {}->http://nexus.rehlds.org][total kept alive: 0; route allocated: 0 of 5; total allocated: 0 of 10]
18:46:29.021 [DEBUG] [org.apache.http.impl.conn.PoolingClientConnectionManager] Connection leased: [id: 8][route: {}->http://nexus.rehlds.org][total kept alive: 0; route allocated: 1 of 5; total allocated: 1 of 10]
18:46:29.236 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnectionOperator] Connecting to nexus.rehlds.org:80
18:48:40.085 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnection] Connection org.apache.http.impl.conn.DefaultClientConnection@5512520e closed
18:48:40.085 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnection] Connection org.apache.http.impl.conn.DefaultClientConnection@5512520e shut down
18:48:40.086 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnection] Connection org.apache.http.impl.conn.DefaultClientConnection@5512520e closed

**Comment by stamepicmorg** [comment]
unfortunately rehlds.org is unavailable now

**Comment by stamepicmorg** [comment]
linked issues:
- https://github.com/theAsmodai/metamod-r/issues/54
- https://github.com/theAsmodai/metamod-r/issues/56
- https://github.com/dreamstalker/rehlds/issues/924
- https://github.com/dreamstalker/gradle-cpp-plugin/issues/1

**Comment by stamepicmorg** [comment]
hello. compiling problem resolved by migrating to GithubActions https://github.com/theAsmodai/metamod-r/pull/57

you could look at worktflow to implement manual build of build.

later i will update official wiki,

**Comment by stamepicmorg** [comment]
resolved https://github.com/theAsmodai/metamod-r/pull/57
