### ISSUE TITLE
[to do] try to add guthub actions to compile metamod-r

### ISSUE THREAD

**Issue by stamepicmorg** [theAsmodai/metamod-r#56]
[to do] try to add guthub actions to compile metamod-r

**Comment by hajimura** [comment]
ha-ha

**Comment by stamepicmorg** [comment]
[ ] resolve dependencies with gradle
[ ] update gradleconfig
[ ] migrate to github actions

**Comment by stamepicmorg** [comment]
linked issues:
- https://github.com/theAsmodai/metamod-r/issues/54
- https://github.com/theAsmodai/metamod-r/issues/56
- https://github.com/dreamstalker/rehlds/issues/924
- https://github.com/dreamstalker/gradle-cpp-plugin/issues/1

**Comment by stamepicmorg** [comment]
resolved by https://github.com/theAsmodai/metamod-r/pull/57
