### ISSUE TITLE
Bugreport form don't work

### ISSUE THREAD

**Issue by wopox1337** [theAsmodai/metamod-r#66]
```
There is a problem with this template

YAML syntax error: (): did not find expected key while parsing a block mapping at line 1 column 1.
```

@stamepicmorg check this alerts
- https://github.com/theAsmodai/metamod-r/blob/feature/github-improvements/.github/ISSUE_TEMPLATE/template-bug.yml

**Comment by stamepicmorg** [comment]
![image](https://github.com/theAsmodai/metamod-r/assets/1307229/62ad392e-1be0-497c-a642-abd8ac85f06b)
![image](https://github.com/theAsmodai/metamod-r/assets/1307229/1ea033a3-284a-4a48-ba14-f9c9c3bb6363)
