### ISSUE TITLE
[BUG]: Segmentation fault error in "exit" mode

### ISSUE THREAD

**Issue by likux35** [theAsmodai/metamod-r#68]
### Contact Details (optional)

starkus.lukas@inbox.lt

### What happened?

A bug happened after used "exit" all the time with "segmentation fault"
error.
To fix that issue, I recommend remove and revert back from that change to original one:
https://github.com/theAsmodai/metamod-r/commit/ec926a611f4d225bb433609bf827269ad8482618

### Metamod-r Version

1.3.0.138 (Default)

### AMX Mod X Version

1.10.x

### What engine are you seeing the problem on?

reHLDS

### What version of engine are you seeing the problem on?

reHLDS (3.13.0.788)

### What OS are you seeing the problem on?

Linux

### What OS version are you seeing the problem on?

Debian 11

### Relevant log output

exit
L 01/20/2024 - 21:06:40: [META] ini: Begin re-reading plugins list: /root/jail/cstrike/addons/metamod/plugins.ini
L 01/20/2024 - 21:06:40: [META] ini: Read plugin config for: AMX Mod X
L 01/20/2024 - 21:06:40: [META] ini: Read plugin config for: Reunion
L 01/20/2024 - 21:06:40: [META] ini: Read plugin config for: Rechecker
L 01/20/2024 - 21:06:40: [META] ini: Read plugin config for: VoiceTranscoder
L 01/20/2024 - 21:06:40: [META] ini: Read plugin config for: SafeNameAndChat
L 01/20/2024 - 21:06:40: [META] ini: Read plugin config for: LocalizeBug Fix
L 01/20/2024 - 21:06:40: [META] ini: Finished reading plugins list: /root/jail/cstrike/addons/metamod/plugins.ini; Found 6 plugins
L 01/20/2024 - 21:06:40: [META] dll: Updating plugins...
L 01/20/2024 - 21:06:40: [META] dll: Finished updating 15 plugins; kept 6, loaded 0, unloaded 0, reloaded 0, delayed 0
L 01/20/2024 - 21:06:40: [META] dll: Rebuilding callbacks...
L 01/20/2024 - 21:06:40: [META] dll: Callbacks rebuilded.
L 01/20/2024 - 21:06:40: Server shutdown
L 01/20/2024 - 21:06:40: Log file closed
Segmentation fault
Add "-debug" to the ./hlds_run command line to generate a debug.log to help with solving this problem
Sat Jan 20 21:06:40 EET 2024: Server restart in 10 seconds

**Comment by s1lentq** [comment]
Resolves by 096f438
