### ISSUE TITLE
AMXModX-dev 1.8.3+ module automatic load fail

### ISSUE THREAD

**Issue by souvikdas95** [theAsmodai/metamod-r#7]
Apparently, modules are either not automatically getting loaded or there's some issue with linking modules on demand by plugins when metamod-r is used. I had to manually set 'em up in amxmodx/configs/modules.ini to get 'em working. I have observed this thing since commits of this month.

This doesn't happen when used with metamod-p.

Please check @theAsmodai

**Comment by theAsmodai** [comment]
I know about the problem

**Comment by theAsmodai** [comment]
Fixed in https://github.com/theAsmodai/metamod-r/commit/3f25635fa5c76516dec65b959244a53f4bd446b3
